### ISSUE TITLE
Kedy a ako použiť sslContextAlgorithm?

### ISSUE THREAD

**Issue by uzba** [l-ra/openeet#13]
Snažil som sa prísť na to, kedy a ako použiť metódy `sslContextAlgorithm()` a `sslEnabledProtocols()` triedy Builder. Do certifikátov sa veľmi nevyznám, študovanie zdrojákov veľmi nepomohlo, ale narazil som asi na chybu. Podľa mňa je chyba v metóde `EetRegisterRequest.sendRequest()`, podmienka by mala byť `trustKeyStore==null`.

```
if(trustKeyStore!=null)
   sslCtx.init(null,new TrustManager[]{ new EetTrustManager() },null);
else
   sslCtx.init(null,new TrustManager[]{ new EetTrustManager(trustKeyStore) },null);
```

**Comment by l-ra** [comment]
Preneseno do repozitare openeet-java

**Comment by l-ra** [comment]
V repozitari openeet-java opraveno.
