### ISSUE TITLE
.Net pull request

### ISSUE THREAD

**Issue by HightowerCZ** [l-ra/openeet#15]
Ahoj, vytvoril jsem pull request, jestli se na to podivas. Asi nema smysl pokracovat v .Netu. Na webu je uz dnes vic knihoven zpracovanejch vic .netovym zpusobem...

**Comment by l-ra** [comment]
Ahoj, diky za praci. V mezicase jsem restrukturalizoval repozitare. V zakladnim OpenEET neni zadny kod. Vsechen kod je presunut do jednotlivych repozitaru per platforma. Co se budoucnosti openeet-lite c#/.net, ponecham ho v zakladnim tvaru se zachovanim logiky Java implementace s tim, ze casem ho zprovoznim v prostredi .NET Core, kde neni ani XMLDSig, ani WS-Security.. Tam dava tahle limitovana implementace bez zavislosti smysl.

**Comment by l-ra** [comment]
Ve stavu,  v jakem je, neni mozne aplikovat.

**Comment by HightowerCZ** [comment]
OK, co s tim?

**Comment by l-ra** [comment]
Zkuste aplikovat ve forku  https://github.com/vlastikcocek/  nebo ponechte u sebe. Ja bych si rad nechal .NET verzi co nejpodobnejsi Java verzi pro pripadne budouci synchronni upravy.
