### ISSUE TITLE
Changing Certificate

### ISSUE THREAD

**Issue by wandesky** [l-ra/openeet#16]
Hi,
I have a visual studio solution in C# that so far is able to receive FIK in playground mode. I have tried to change the certificate to the one my client uses but I keep getting an error message "Invalid signing of SOAP messages". Please reply in English because I am not conversant with Czech language.
Thank you.

**Comment by l-ra** [comment]
Can you show the code you use to set up the request builder?

**Comment by VeselyJan92** [comment]
It guess it's a problem with checking out the project from Github. Go to templates folder and change line end character from CR-LF to just LF.

**Comment by wandesky** [comment]
The solution I am using I got from https://drive.google.com/open?id=0B2B4_OfsI25pQlM5VmNLUGliUU0  You can have a look at it and help me figure out how I can change change the certificate.

**Comment by l-ra** [comment]
Unfortunately the library you use is not the library which is maintained in this repository. I'm not able to help as I  don't know the library you use.

**Comment by wandesky** [comment]
Thanks for the concern i-ra.

**Comment by l-ra** [comment]
You are welcome. I'm closing the issue.
