### ISSUE TITLE
Změna certifikátů

### ISSUE THREAD

**Issue by LoockyCZ** [l-ra/openeet#18]
24.4.2018 proběhla změna certifikátu na PG. Tato změna je plánována i pro produkční prostředí.
viz http://www.etrzby.cz/cs/oznameni-pro-vyvojare

**Comment by vlastikcocek** [comment]
ahoj, nenasel jsem kde jsou k dispozici nove certifikáty pro test na PG.
 Test podpisu pres certifikat EET_CA1_Playground-CZ00000019.p12 probehl ok.

<?xml version="1.0" encoding="UTF-8"?>
<soapenv:Envelope xmlns:eet="http://fs.mfcr.cz/eet/schema/v3" xmlns:wsu="http://docs.oasis-open.org/wss/2004/01/oasis-200401-wss-wssecurity-utility-1.0.xsd" xmlns:wsse="http://docs.oasis-open.org/wss/2004/01/oasis-200401-wss-wssecurity-secext-1.0.xsd" xmlns:soapenc="http://schemas.xmlsoap.org/soap/encoding/" xmlns:soapenv="http://schemas.xmlsoap.org/soap/envelope/"><soapenv:Header/><soapenv:Body><eet:Odpoved><eet:Hlavicka uuid_zpravy="1dbbc73e-6af0-4016-ba4b-3464e1354c6c" dat_odmit="2018-05-15T00:11:52+02:00"/><eet:Chyba kod="0" test="true">Datovou zpravu evidovane trzby v overovacim modu se podarilo zpracovat</eet:Chyba></eet:Odpoved></soapenv:Body></soapenv:Envelope>

**Comment by vlastikcocek** [comment]
<eet:Odpoved><eet:Hlavicka uuid_zpravy="18c77e2b-fccc-42bb-829f-c2dfd20d7f4f" bkp="397438B3-A93212D7-F398D0A9-CFC54D23-BED7065F" dat_prij="2018-05-15T00:27:22+02:00"/><eet:Potvrzeni fik="29915526-39c7-4cab-94f2-43f52509e228-ff" test="true"/></eet:Odpoved></soapenv:Body></soapenv:Envelope>

**Comment by l-ra** [comment]
Změna se týká TLS certifikátů serverů EET. V Java verzi je součástí kódů speciální trust store, který musím aktualizovat.

**Comment by l-ra** [comment]
Do java verze jsem prijal pull request s aktualizovanym truststorem. Diky za prispevek
