### ISSUE TITLE
SOAP signature is not valid

### ISSUE THREAD

**Issue by VeselyJan92** [l-ra/openeet#2]
I cloned project and I am getting ERR SOAP signature is not valid, do you have any idea how to fix it?

**Comment by l-ra** [comment]
Could you please elaborate more on the issue? Which platform (Java, C#, Shell). What is your code example?

**Comment by VeselyJan92** [comment]
So the first problem is formatting of amounts in XML, **java** uses locale formatting if there isn´t  Locale parametr in a `format` method  therefore in XML there is parametr: `celk_trzba="100,00"`, which use Czech sign you need to use: `String.format(Locale.US, "%.2f", amount)` in order to get a dot. And the second problem I haven´t figure out yet. It is in: `assertTrue(validateXmlDSig(signed, data.getCertificate()));`, But I didn't change anything else except the `amount` method.

**Comment by VeselyJan92** [comment]
**Solved** for those who use IntelliJ when you clone project you need to change manually line separators to LF for all templates.

**Comment by l-ra** [comment]
Bad issue mentioned in closing commit.
