### ISSUE TITLE
Nastavování příznaku Overeni v .Net

### ISSUE THREAD

**Issue by ZephyCZ** [l-ra/openeet#8]
V "openeet/dotnet/openeet-lite/EetRegisterRequest.cs" na řádku 137, je špatně vyhodnocen vstup.

```
public Builder overeni(bool val) {
   if (val) _overeni=Overeni.PRODUKCNI;
   else _overeni=Overeni.OVEROVACI;
      return this;
}
```

Když přijde, že je val=true, tak by mělo být nastaveno: _overeni=Overeni.OVEROVACI. 
A když je val=false, tak _overeni=Overeni.PRODUKCNI. 
Nyní je to naopak. 
V javovské části je to opraveno, takže se to týká jen v té .NET části. 
Tzn. mělo by to být takto:

```
public Builder overeni(bool val) {
   if (val) _overeni=Overeni.OVEROVACI;
   else _overeni = Overeni.PRODUKCNI;
      return this;
}
```

Jinak super práce, díky moc.

**Comment by l-ra** [comment]
Jen tak pro jistotu se zeptam :-) ... nebylo by mozne to poslat jako pull request :-) ?
